POST http://localhost:3000/products
content-type: application/json

{
	"name": "My product 1",
	"detail": "My product detail",
	"amount": 100,
	"price": 100
}

###
GET http://localhost:3000/products
content-type: application/json

###
GET http://localhost:3000/products/65ff5b1e1f6ec1939fea4883
content-type: application/json

###
PUT http://localhost:3000/products/65ff5b1e1f6ec1939fea4883
content-type: application/json

{
	"amount": 1000
}

###
DELETE http://localhost:3000/products/65ff5b1e1f6ec1939fea4883
content-type: application/json